

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
  
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
